% runTrafficSimulationCircularSquare

o.roadArray = struct(...
    ...% road idx  1   2   3   4
    'nodeStart',  {1,  2,  3,  4  },...
    'nodeEnd',    {2,  3,  4,  1  },...
    'length',     {200,200,200,200},...
    'imageRoad',  {0,  0,  0,  0  }...
);

o.nodeArray = struct(...
    ...% node idx  1  2  3  4
    'spawnRate',  {1, 0.2, 0.3, 0.4},...
    'destChance', {1, 1, 1, 1}...
);

% visArray can be omitted when simulating, but it is necessary for
% visualization
o.visArray = struct(...
    ...% node idx  1    2     3     4
    'x',          {0.5, -0.5, -0.5, 0.5},...
    'y',          {0.5, 0.5,  -0.5, -0.5}...
);

% car speed
o.vmax = 22.2;  % meters/second
o.dmin = 5;  % meters
o.dmax = 100;  % meters
% Simulation speed
o.simulationTime = 100;  % in seconds
o.dt = 0.1;  % in seconds

% Run Simulation
TrafficSimulation(o);
