% runTrafficSimulationTest

o.roadArray = struct(...
    'nodeStart',  {1, 2},...
    'nodeEnd',    {2, 1},...
    'length',     {5, 5},...
    'imageRoad',  {2, 1}...
);

o.nodeArray = struct(...
    'spawnRate',  {1, 1},...
    'destChance', {1, 1}...
);

% car speed
o.vmax = 22.2;  % meters/second
o.dmin = 5;  % meters
o.dmax = 100;  % meters
% Simulation speed
o.simulationTime = 10;  % in seconds
o.dt = 0.1;  % in seconds

% Run Simulation
TrafficSimulation(o);
